### ISSUE TITLE
Migration error with django 1.7

### ISSUE THREAD

**Issue by psychok7** [pinax/pinax-notifications#47]
I am using Django 1.7 with pinax-notifications 2.1.0 and i get an error when i try to do a migrate:

Traceback:

```
(test)vagrant@vagrant:/vagrant$ python manage.py migrate --settings=test.settings.local
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 63, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/vagrant/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 17, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/vagrant/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 48, in __init__
    self.build_graph()
  File "/home/vagrant/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 245, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/home/vagrant/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/migrations/graph.py", line 46, in add_dependency
    "Migration %s dependencies reference nonexistent parent node %r" % (migration, parent)
KeyError: u"Migration notifications.0001_initial dependencies reference nonexistent parent node (u'contenttypes', u'0002_remove_content_type_name')"
``` 

WORKAROUND: Downgrade to `pinax-notifications==2.0.1`

**Comment by paltman** [comment]
Should be fixed in #48
