### ISSUE TITLE
Pinax conflicting with django-notifications-hq

### ISSUE THREAD

**Issue by odero** [pinax/pinax-notifications#59]
I've been using django-notifications-hq (https://github.com/django-notifications/django-notifications) along with the old version of pinax-notifications (i.e. when it was still django-notification). The problem now is that I cannot upgrade to pinax-notifications because of an application name conflict.

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/code/.pyenv/versions/testapp-2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/code/.pyenv/versions/testapp-2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/code/.pyenv/versions/testapp-2.7/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/code/.pyenv/versions/testapp-2.7/lib/python2.7/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: notifications
```

Any easy way to resolve this?

**Comment by ossanna16** [comment]
@odero Would you mind joining our Slack team (http://slack.pinaxproject.com) and posting your question in the #pinax-notifications channel? We're usually able to help people faster in Slack. Thank you!

**Comment by grahamu** [comment]
This is resolved after adding namespacing in the recent update supporting Django v2.0
